Nome = str(input('Qual seu nome completo? ')).strip()
up = Nome.upper()
down = Nome.lower()
total = (len(Nome)-Nome.count(' '))
quantidade = len(Nome.split()[0])
print('=' * 12)
print("Em maiúsculo: ", up)
print("Em minúsculo: ", down)
print("Quantas letras no total: ", total)
print("Quantas letras no primeiro nome: ", quantidade)
print('=' * 12)
