Nome = str(input('Qual seu nome completo? ')).strip()
up = Nome.upper()
down = Nome.lower()
total = (len(Nome)-Nome.count(' '))
quantidade = len(Nome.split()[0])
print('=' * 12)
print("\033[1;44mEm maiúsculo: ", up, "\033[m")
print("\033[1;45mEm minúsculo: ", down, "\033[m")
print("\033[1;46mQuantas letras no total: ", total, "\033[m")
print("\033[1;47mQuantas letras no primeiro nome: ", quantidade, "\033[m")
print('=' * 12)
